DATA:
    ROOT: '/kaggle/input/ucf-crime-full'
    TRAIN_FILE: '/home/quanghieupham/Coding/VideoX/X-CLIP/annotations/train_formated.json'
    VAL_FILE: '/home/quanghieupham/Coding/VideoX/X-CLIP/annotations/train_formated.json'
    DATASET: ucf-crime
    NUM_FRAMES: 32
    NUM_CLASSES: 14
    LABEL_LIST: 'labels/ucf-crime.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 2
    ACCUMULATION_STEPS: 8
    EPOCHS: 1
    LR: 2.e-6
TEST:
    BATCH_SIZE: 2